FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

ENV TZ=Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install tensorboard
RUN pip install torch
RUN pip install torchvision
RUN pip install jupyter
RUN pip install notebook
RUN pip install opencv-python
RUN pip install numpy
RUN pip install matplotlib

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    zlib1g-dev \
    libopenmpi-dev \
    ffmpeg \
    software-properties-common \
    lsb-release \
    sed \
    tmux \
    python3-opengl \
    && rm -rf /var/lib/apt/lists/*
